name: Build and push to development
on:
    pull_request:

jobs:
    build:
        uses: ./.github/workflows/gcr-build.yml
        with:
            environment: dev
        secrets:
            GCR_SA_KEY: ${{ secrets.GCR_SA_KEY }}
            REACT_ENV_B64: ${{ secrets.REACT_ENV_B64 }}
