name: Build and push to development
on:
    pull_request:
        branches-ignore:
            - main
jobs:
    build:
        uses: ./.github/workflows/gcr-build.yml
        with:
            environment: dev
        secrets:
            GCR_SA_KEY: ${{ secrets.GCR_SA_KEY }}
            FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
