name: Build and push to artifact registry
# https://github.com/google-github-actions/setup-gcloud
on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: environment to deploy to
        required: true
    secrets:
      GCR_SA_KEY:
        required: true
      REACT_ENV_B64:
        required: true

env:
  GCR_PROJECT: ${{ vars.GCR_PROJECT }}
  RUN_REGION: europe-north1
  SERVICE_NAME: tiira-watcher-ui
  REPO_NAME: tiira-watcher-repo
  REACT_ENV_B64: ${{ secrets.REACT_ENV_B64 }}

jobs:
  build:
    name: Build React App
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Substitute env vars
        run: |
          echo "$REACT_ENV_B64" | base64 -d > .production.env

      - name: Setup GCloud Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCR_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Set version
        run: echo "VERSION=$(fgrep '"version"' package.json | cut -d "\"" -f 4)" | tee -a $GITHUB_ENV

      - name: Store version file
        run: |
          echo $VERSION > ui_version.txt
          gcloud storage cp ui_version.txt gs://${{ env.GCR_PROJECT }}-terraform-backend/app_versions/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Authenticate to artifact registry
        run: |
          gcloud auth configure-docker ${{ env.RUN_REGION }}-docker.pkg.dev --quiet

      - name: Build
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          tags: "${{ env.RUN_REGION }}-docker.pkg.dev/${{ env.GCR_PROJECT }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:${{ env.VERSION }}"
